print("드디어 성공")
print("테스트 파일이 성공적으로 실행되었습니다.")
print("이제 코드를 커밋할 준비가 되었습니다.")
print("테스트 완료!")
print(123)
print(1.23)
name = "홍길동"
age = 22
print(name)
print(age)
name = input("이름을 입력하세요: ")
age = input("나이를 입력하세요: ")
print("이름:", name)
print("나이:", age)
a = int(input("첫 번째 숫자를 입력하세요: "))
b = int(input("두 번째 숫자를 입력하세요: "))
sum = a + b
print("두 숫자의 합은:", sum)
a = int(input("2: "))
print(a)
print(3 + 4)
print(5 / 3)
print(5 // 3)
print(5 % 3)
print(2 ** 3)
print( 3 > 2)
print ( 3 < 2)
print( 3 >= 2)
print( 3 <=2 )
print( 3 == 2)
print( 3!=2 )
print( (3 > 2) and (3 < 2))
print( (3 > 2) or (3 < 2))
print( not (3 > 2))
print( 3 + 4 * 2)
print( (3 + 4) * 2)
print(7 / 3 + 2 * 3 - 1)
